version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./images/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./www:/usr/share/nginx/html
            - ./logs:/var/log/nginx
        depends_on:
            - php
    php:
        # build: ./images/php
        image: books_php
        env_file:
            - ".env"
        depends_on:
            - dbmaster
            - dbslave
        volumes:
            - ./www:/usr/share/nginx/html
    php2:
        # build: ./images/php
        image: books_php
        depends_on:
            - dbmaster
            - dbslave
        volumes:
            - ./www:/usr/share/nginx/html
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        env_file:
            - ".env"
        environment:
            - PMA_ARBITRARY=1
        restart: always
        depends_on:
            - dbmaster
            - dbslave
    dbmaster:
        image: mysql
        env_file:
            - ".env"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysqlMaster:/var/lib/mysql
            - ./images/mysql/master:/etc/mysql/conf.d/
    dbslave:
        image: mysql
        env_file:
            - ".env2"
        environment:
            - REPLICATION_MASTER_HOST='dbmaster'
            - REPLICATION_MASTER_USER='user'
            - REPLICATION_MASTER_PASSWORD='123'
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - "3307:3306"
        volumes:
            - ./data/mysqlSlave:/var/lib/mysql
            - ./images/mysql/slave:/etc/mysql/conf.d/
        depends_on:
            - 'dbmaster'